// @filename: IANATimezones.ts

/*
 * Copyright 2023 Pedro Paulo Teixeira dos Santos

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

type IANATimezones =
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' }               |
    { code: 'Africa/Accra', display: 'Africa/Accra' }                   |
    { code: 'Africa/Addis_Ababa', display: 'Africa/Addis_Ababa' }       |
    { code: 'Africa/Algiers', display: 'Africa/Algiers' }               |
    { code: 'Africa/Bamako', display: 'Africa/Bamako' }                 |
    { code: 'Africa/Bangui', display: 'Africa/Bangui' }                 |
    { code: 'Africa/Banjul', display: 'Africa/Banjul' }                 |
    { code: 'Africa/Bissau', display: 'Africa/Bissau' }                 |
    { code: 'Africa/Blantyre', display: 'Africa/Blantyre' }             |
    { code: 'Africa/Brazzaville', display: 'Africa/Brazzaville' }       |
    { code: 'Africa/Bujumbura', display: 'Africa/Bujumbura' }           |
    { code: 'Africa/Cairo', display: 'Africa/Cairo' }                   |
    { code: 'Africa/Casablanca', display: 'Africa/Casablanca' }         |
    { code: 'Africa/Ceuta', display: 'Africa/Ceuta' }                   |
    { code: 'Africa/Conakry', display: 'Africa/Conakry' }               |
    { code: 'Africa/Dakar', display: 'Africa/Dakar' }                   |
    { code: 'Africa/Dar_es_Salaam', display: 'Africa/Dar_es_Salaam' }   |
    { code: 'Africa/Djibouti', display: 'Africa/Djibouti' }             |
    { code: 'Africa/Douala', display: 'Africa/Douala' }                 |
    { code: 'Africa/El_Aaiun', display: 'Africa/El_Aaiun' }             |
    { code: 'Africa/Freetown', display: 'Africa/Freetown' }             |
    { code: 'Africa/Gaborone', display: 'Africa/Gaborone' }             |
    { code: 'Africa/Harare', display: 'Africa/Harare' }                 |
    { code: 'Africa/Johannesburg', display: 'Africa/Johannesburg' }     |
    { code: 'Africa/Juba', display: 'Africa/Juba' }                     |
    { code: 'Africa/Kampala', display: 'Africa/Kampala' }               |
    { code: 'Africa/Khartoum', display: 'Africa/Khartoum' }             |
    { code: 'Africa/Kigali', display: 'Africa/Kigali' }                 |
    { code: 'Africa/Kinshasa', display: 'Africa/Kinshasa' }             |
    { code: 'Africa/Lagos', display: 'Africa/Lagos' }                   |
    { code: 'Africa/Libreville', display: 'Africa/Libreville' }         |
    { code: 'Africa/Lome', display: 'Africa/Lome' }                     |
    { code: 'Africa/Luanda', display: 'Africa/Luanda' }                 |
    { code: 'Africa/Lubumbashi', display: 'Africa/Lubumbashi' }         |
    { code: 'Africa/Lusaka', display: 'Africa/Lusaka' }                 |
    { code: 'Africa/Malabo', display: 'Africa/Malabo' }                 |
    { code: 'Africa/Maputo', display: 'Africa/Maputo' }                 |
    { code: 'Africa/Maseru', display: 'Africa/Maseru' }                 |
    { code: 'Africa/Mbabane', display: 'Africa/Mbabane' }               |
    { code: 'Africa/Mogadishu', display: 'Africa/Mogadishu' }           |
    { code: 'Africa/Monrovia', display: 'Africa/Monrovia' }             |
    { code: 'Africa/Nairobi', display: 'Africa/Nairobi' }               |
    { code: 'Africa/Ndjamena', display: 'Africa/Ndjamena' }             |
    { code: 'Africa/Niamey', display: 'Africa/Niamey' }                 |
    { code: 'Africa/Nouakchott', display: 'Africa/Nouakchott' }         |
    { code: 'Africa/Ouagadougou', display: 'Africa/Ouagadougou' }       |
    { code: 'Africa/Porto-Novo', display: 'Africa/Porto-Novo' }         |
    { code: 'Africa/Sao_Tome', display: 'Africa/Sao_Tome' }             |
    { code: 'Africa/Timbuktu', display: 'Africa/Timbuktu' }             |
    { code: 'Africa/Tripoli', display: 'Africa/Tripoli' }               |
    { code: 'Africa/Tunis', display: 'Africa/Tunis' }                   |
    { code: 'Africa/Windhoek', display: 'Africa/Windhoek' }             |

    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' } |
    { code: 'Africa/Abidjan', display: 'Africa/Abidjan' }
